services:
  webapp:
    build: .
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - DEBUG_HEADERS=0
      - REDIS_URL=tcp://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
        - redis-data:/data
    
  lb:
    image: nginx:1.14.2
    volumes:
        - ./lb-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - 8001:80
    links:
        - webapp
volumes:
    redis-data:
           